sudo: required
services:
  - docker

before_install:
  - sudo /etc/init.d/postgresql stop

install:
  - docker-compose up --build
  - sleep 5

script:
  - docker images
  - docker ps
  - curl localhost:4000

after_script:
  - docker-compose down