version: "3"
services:
  api:
    container_name: api
    # restart: always
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/www/src
    depends_on:
      - postgres_db
  postgres_db:
    container_name: postgres_db
    # restart: always
    image: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"